### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PucklaJ** [PucklaJ/samurai-select#2]
This is a list of issues I encountered and for which I don't want to open a separate issue.

+ [x] When pressing ESC when using regions it outputs the last selected region
+ [x] The regions flag should be set to auto if no argument is specified
+ [x] When selecting outputs the cursor can be between outputs and the application crashes if clicked
+ [x] Text is still shown when selecting regions even if no region is selected
+ [x] Add more format specifiers (e.g. output name)
+ [x] Add man page
+ [x] Make sure shown text is equal to output selection
+ [x] Select floating windows before tiled ones on Hyprland
